title       = "imf"
baseURL     = "https://imf-cli.tamnd.com/"
description = "A command line for imf."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/imf-cli"
